version: '3.8'

services:
  maildev:
    image: maildev/maildev
    container_name: app_maildev
    ports:
      - "1080:1080" 
      - "1025:1025"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    container_name: app_backend
    build:
      context: ./backend
      dockerfile: Docker/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env 
    environment:
      NODE_ENV: development
      PORT: 3000
      EMAIL_HOST: maildev 
      EMAIL_PORT: 1025   
      EMAIL_USER: ""
      EMAIL_PASSWORD: ""
      EMAIL_FROM: "no-reply@appguia.com"
    volumes:
      - ./backend:/app:rw
    depends_on:
      - maildev
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: app_frontend
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app:rw
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge