services:
  backend:
    container_name: app_backend
    build:
      context: ./backend
      dockerfile: Docker/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env 
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./backend:/app:rw
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: app_frontend
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app:rw
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge